Add ability to pull student repos issue #8
github/gh-classroom pull request #39
Opened 2023-09-19 17:32 UTC by shanep

### What are you trying to accomplish?

Change the default behavior when cloning student repos to skip any repos that have already been cloned. Add in a command line flag to allow existing repos to be sync'd instead of a full clone.

Fix issue #14
Implements Feature #8

### What approach did you choose and why?

Instead of doing a fresh clone every single time, skip any repos that have already been cloned and give the user a new command line flag to sync. If the user wants a fresh clone then they can already use the --directory flag to do so.

UPDATE: This change should take some pressure off your endpoint :)

### What should reviewers focus on?

I couldn't see anywhere in the documentation where the **gh** cli allows you to pass a path when performing a **sync** so I had to change the working directory. If there is a better way to do a sync with the gh client please let me know :)

2023-09-24 20:06 UTC, NukeManDan approved these changes
Will help a lot for using this tool for sure! :heart_eyes:

2023-09-26 19:52 UTC, zrdaley requested changes
@shanep thank you for this contribution!

I was chatting with @RyanHecht and in order to be consistent with typical git commands, it would make more sense to have a `gh classroom pull` command rather than a `--sync` flag on the `gh classroom clone` command. 

If you could take some time to make this into it's own command then I'd be happy to re-review.

2023-09-26 21:07 UTC, shanep commented
@zrdaley no problem! I like that approach its keeps the semantics all lined up and doesn't overload the clone command :) I will get it all updated as soon as I can :)

2023-09-26 22:55 UTC, shanep reviewed
Changes have been pushed to the branch and are ready for review :)

2023-09-28 16:02 UTC, zrdaley commented on cmd/gh-classroom/clone/student-repos/student-repos.go
> +				if _, err := os.Stat(clonePath); os.IsNotExist(err) {
Thank you for adding this check ✨

2023-09-29 22:06 UTC, shanep commented
Updated to align with the clone command for both student repos and starter code :)

2023-10-02 23:37 UTC, shanep reviewed
I think this should be good to go now. However, please let me know if you still see any issues :)

2023-10-03 15:14 UTC, zrdaley commented on cmd/gh-classroom/pull/student-repos/student-repos.go
> +
```suggestion
```

2023-10-03 15:15 UTC, zrdaley approved these changes
Small nit, but otherwise LGTM! Thank you for this contribution.

2023-10-03 15:36 UTC, shanep commented
> Small nit, but otherwise LGTM! Thank you for this contribution.

No worries :) Truly appreciate the feedback! Excited to see this get merged.

2023-10-03 15:43 UTC, merged

2023-10-03 15:47 UTC, zrdaley commented
Once https://github.com/github/gh-classroom/actions/runs/6395315615 is green you should be able to upgrade the CLI and use this command.